import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'zh' | 'ja' | 'ko';

export type LanguageOption = {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
};

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'EN' },
  { code: 'zh', label: 'Chinese', nativeLabel: '中文' },
  { code: 'ja', label: 'Japanese', nativeLabel: '日本語' },
  { code: 'ko', label: 'Korean', nativeLabel: '한국어' },
];

type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  isLoading: boolean;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Onboarding
    'onboarding.back': 'Back',
    'onboarding.q1.question': 'Do you prefer...',
    'onboarding.q1.opt1': 'Neutrals',
    'onboarding.q1.opt2': 'Color',
    'onboarding.q1.opt3': 'Mostly neutrals with some color',
    'onboarding.q1.opt4': "I'm trying to experiment more",
    'onboarding.q2.question': 'Do you ever feel overwhelmed by color choices when shopping?',
    'onboarding.q2.opt1': 'Yes, all the time!',
    'onboarding.q2.opt2': 'Sometimes',
    'onboarding.q2.opt3': 'Not really',
    'onboarding.q2.opt4': 'I just grab and go',
    'onboarding.q3.question': 'Have you ever taken a color analysis test?',
    'onboarding.q3.opt1': 'Yes, I know my season',
    'onboarding.q3.opt2': 'Yes, but I forgot my results',
    'onboarding.q3.opt3': 'No, but I want to!',
    'onboarding.q3.opt4': "No, what's that?",
    'onboarding.q4.question': 'Want to try colors on yourself?',
    'onboarding.q4.opt1': 'Yes, that would be amazing!',
    'onboarding.q4.opt2': "Sure, I'm curious",
    'onboarding.q4.opt3': "Maybe, if it's easy",
    'onboarding.q4.opt4': 'Maybe later',
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.description': 'Change app language',
    'settings.availableCapes': 'Available Capes',
    'settings.capePalettes': 'Cape Palettes',
    'settings.capePalettes.enabled': 'enabled',
    'settings.createCustomCape': 'Create Custom Cape',
    'settings.createCustomCape.description': 'Design your own color palette',
    'settings.camera': 'Camera',
    'settings.defaultFrontCamera': 'Default Front Camera',
    'settings.defaultFrontCamera.description': 'Use front camera when opening cape',
    'settings.mirrorFrontCamera': 'Mirror Front Camera',
    'settings.mirrorFrontCamera.description': 'Flip image like a mirror',
    'settings.cameraPermissions': 'Camera Permissions',
    'settings.cameraPermissions.description': 'Manage camera access in Settings',
    'settings.cape': 'Cape',
    'settings.capeOpacity': 'Cape Opacity',
    'settings.capeOpacity.description': 'How visible the color overlay appears',
    'settings.opacity.light': 'Light',
    'settings.opacity.medium': 'Medium',
    'settings.opacity.strong': 'Strong',
    'settings.opacity.full': 'Full',
    'settings.share': 'Share',
    'settings.shareWithFriends': 'Share with Friends',
    'settings.shareWithFriends.description': 'Spread the word about Color Cape',
    'settings.subscription': 'Subscription',
    'settings.manageSubscription': 'Manage Subscription',
    'settings.manageSubscription.description': 'View or manage your subscription',
    'settings.appData': 'App Data',
    'settings.clearLastViewed': 'Clear Last Viewed Palette',
    'settings.clearLastViewed.description': 'Remove the last viewed palette from Home',
    'settings.clearLastViewed.empty': 'No last viewed palette to clear',
    'settings.clearSavedResult': 'Clear Saved Test Result',
    'settings.clearSavedResult.description': 'Remove your saved seasonal color result',
    'settings.clearSavedResult.empty': 'No saved test result to clear',
    'settings.resetSettings': 'Reset Settings',
    'settings.resetSettings.description': 'Restore camera and cape settings to defaults',
    'settings.resetSettings.atDefaults': 'Settings are already at defaults',
    'settings.logOut': 'Log Out',
    'settings.legal': 'Legal',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsOfService': 'Terms of Service',
    // Alerts
    'alert.resetSettings.title': 'Reset Settings',
    'alert.resetSettings.message': 'This will reset camera, cape settings, and delete custom capes. Are you sure?',
    'alert.cancel': 'Cancel',
    'alert.reset': 'Reset',
    'alert.clear': 'Clear',
    'alert.clearLastViewed.title': 'Clear Last Viewed',
    'alert.clearLastViewed.message': 'This will remove the last viewed palette from the home screen. Are you sure?',
    'alert.clearSavedResult.title': 'Clear Saved Result',
    'alert.clearSavedResult.message': 'This will remove your saved test result from the home screen. Are you sure?',
    'alert.logOut.title': 'Log Out',
    'alert.logOut.message': 'This will clear your onboarding progress and show the welcome screens again.',
    'alert.logOut.confirm': 'Log Out',
    // Home screen
    'home.title': 'Color Cape',
    'home.subtitle': 'Discover your perfect color palette',
    'home.tryPalettes': 'Try Palettes',
    'home.tryPalettes.description': 'Use camera to see how different color palettes look on you',
    'home.lastViewed': 'Last viewed:',
    'home.takeTest': 'Take the Test',
    'home.takeTest.description': 'Find your seasonal color palette in a test',
    'home.lastSavedResult': 'Last saved result:',
    'home.customizeCapes': 'Customize Capes',
    'home.customizeCapes.description': 'Toggle palettes, reorder, and create your own custom capes',
    'home.capeOpacity': 'Cape Opacity',
    'home.capeOpacity.description': 'Adjust how visible the color overlay appears',
    'home.current': 'Current:',
    'home.opacity.sheet.title': 'Cape Opacity',
    'home.opacity.sheet.description': 'Choose how visible the color overlay appears on camera',
    // Camera screen
    'camera.loading': 'Loading camera...',
    'camera.permissionTitle': 'Camera Access Required',
    'camera.permissionText': 'We need your permission to access the camera.',
    'camera.continue': 'Continue',
    'camera.noPalettes': 'No palettes enabled. Enable some in Settings.',
    'camera.goToSettings': 'Go to Settings',
    'camera.back': 'Back',
    'camera.save': 'Save',
    'camera.saved': 'Saved!',
    'camera.savedMessage': 'Photo with color overlay saved to your gallery.',
    'camera.permissionNeeded': 'Permission needed',
    'camera.permissionNeededMessage': 'Please grant permission to save photos to your gallery.',
    'camera.error': 'Error',
    'camera.errorSaving': 'Failed to save photo.',
    'camera.colorMode.all8': 'All 8',
    'camera.colorMode.core': 'Core',
    'camera.colorMode.accent': 'Accent',
    'camera.customColors': 'custom colors',
    'camera.colors': 'colors',
    // Test screen
    'test.loading': 'Loading camera...',
    'test.permissionTitle': 'Camera Access Required',
    'test.permissionText': 'We need your permission to show you how colors look on you.',
    'test.continue': 'Continue',
    'test.intro.title': 'Find Your Colors',
    'test.intro.subtitle': 'Answer 6 quick questions to discover your seasonal color palette',
    'test.intro.privacyNote': 'Your photo stays on your device and is never uploaded.',
    'test.intro.startButton': 'Start Test',
    'test.intro.goHome': 'Go back home',
    'test.capture.title': 'Take Your Photo',
    'test.capture.subtitle': 'This will be used for all comparisons',
    'test.capture.instruction': 'Position yourself within the cape outline',
    'test.confirm.title': 'Looking Good!',
    'test.confirm.subtitle': 'Ready to start the color test?',
    'test.confirm.retake': 'Retake',
    'test.confirm.start': 'Confirm & Start',
    'test.compare.swipeHint': 'Swipe to compare',
    'test.compare.choose': 'Choose',
    'test.modal.youSelected': 'You selected',
    'test.modal.cancel': 'Cancel',
    'test.modal.confirm': 'Confirm',
    'test.transition.guide': 'Guide:',
    'test.transition.lookFor': 'Look for:',
    'test.transition.back': 'Back',
    'test.transition.next': 'Next',
    'test.results.colorProfile': 'Your Color Profile',
    'test.results.undertone': 'Undertone:',
    'test.results.value': 'Value:',
    'test.results.chroma': 'Chroma:',
    'test.results.yourMatches': 'Your Matches',
    'test.results.tapToPreview': 'Tap to preview colors',
    'test.results.best': 'Best',
    'test.results.stylingTips': 'Styling Tips for',
    'test.results.saveResult': 'Save Result',
    'test.results.saved': 'Saved!',
    'test.results.retakeTest': 'Retake Test',
    'test.score.cool': 'Cool',
    'test.score.warm': 'Warm',
    'test.score.neutral': 'Neutral',
    'test.score.light': 'Light',
    'test.score.deep': 'Deep',
    'test.score.medium': 'Medium',
    'test.score.bright': 'Bright',
    'test.score.soft': 'Soft',
    'test.transition.undertone': 'Undertone',
    'test.transition.value': 'Value',
    'test.transition.chroma': 'Chroma',
    'test.transition.undertone.title': 'Undertone Test',
    'test.transition.undertone.desc': "Let's find if you have warm or cool undertones",
    'test.transition.value.title': 'Value Test',
    'test.transition.value.desc': "Now let's see if light or deep colors suit you better",
    'test.transition.chroma.title': 'Chroma Test',
    'test.transition.chroma.desc': 'Finally, bright clear colors or soft muted tones?',
    // Customize screen
    'customize.title': 'Customize Capes',
    'customize.customCapes': 'Custom Capes',
    'customize.customCapes.description': 'Create your own color cape palettes',
    'customize.createCustomCape': 'Create Custom Cape',
    'customize.allPalettes': 'All Palettes',
    'customize.allPalettes.description': 'Toggle and reorder your capes',
    'customize.disableAll': 'Disable All',
    'customize.enableAll': 'Enable All',
    'customize.resetToDefaults': 'Reset to Defaults',
    'customize.modal.createTitle': 'Create Custom Cape',
    'customize.modal.editTitle': 'Edit Custom Cape',
    'customize.modal.capeName': 'Cape Name',
    'customize.modal.capeNamePlaceholder': 'Enter cape name',
    'customize.modal.numberOfColors': 'Number of Colors',
    'customize.modal.tapToEdit': 'Tap a color to edit',
    'customize.modal.chooseColor': 'Choose Color',
    'customize.modal.tapToPickColor': 'Tap to pick color',
    'customize.modal.quickColors': 'Quick Colors',
    'customize.modal.importExport': 'Import / Export',
    'customize.modal.import': 'Import',
    'customize.modal.export': 'Export',
    'customize.modal.delete': 'Delete',
    'customize.modal.saveCape': 'Save Cape',
    'customize.import.title': 'Import Cape',
    'customize.import.description': 'Paste the exported cape JSON data below',
    'customize.import.paste': 'Paste from Clipboard',
    'customize.alert.deleteTitle': 'Delete Custom Cape',
    'customize.alert.deleteMessage': 'Are you sure you want to delete this custom cape?',
    'customize.alert.delete': 'Delete',
    'customize.alert.resetTitle': 'Reset Palettes',
    'customize.alert.resetMessage': 'This will reset all palette settings to defaults. Are you sure?',
    'customize.colors': 'colors',
  },
  zh: {
    // Onboarding
    'onboarding.back': '返回',
    'onboarding.q1.question': '你更喜欢...',
    'onboarding.q1.opt1': '中性色',
    'onboarding.q1.opt2': '彩色',
    'onboarding.q1.opt3': '主要是中性色，带一些彩色',
    'onboarding.q1.opt4': '我正在尝试更多实验',
    'onboarding.q2.question': '购物时，你是否曾对颜色选择感到不知所措？',
    'onboarding.q2.opt1': '是的，总是这样！',
    'onboarding.q2.opt2': '有时候',
    'onboarding.q2.opt3': '不太会',
    'onboarding.q2.opt4': '我只是随便拿',
    'onboarding.q3.question': '你做过色彩分析测试吗？',
    'onboarding.q3.opt1': '是的，我知道我的季节类型',
    'onboarding.q3.opt2': '是的，但我忘了结果',
    'onboarding.q3.opt3': '没有，但我想试试！',
    'onboarding.q3.opt4': '没有，那是什么？',
    'onboarding.q4.question': '想在自己身上试试颜色吗？',
    'onboarding.q4.opt1': '是的，那太棒了！',
    'onboarding.q4.opt2': '好的，我很好奇',
    'onboarding.q4.opt3': '也许，如果很简单的话',
    'onboarding.q4.opt4': '以后再说',
    // Settings
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.language.description': '更改应用语言',
    'settings.availableCapes': '可用披风',
    'settings.capePalettes': '披风调色板',
    'settings.capePalettes.enabled': '已启用',
    'settings.createCustomCape': '创建自定义披风',
    'settings.createCustomCape.description': '设计你自己的调色板',
    'settings.camera': '相机',
    'settings.defaultFrontCamera': '默认前置摄像头',
    'settings.defaultFrontCamera.description': '打开披风时使用前置摄像头',
    'settings.mirrorFrontCamera': '镜像前置摄像头',
    'settings.mirrorFrontCamera.description': '像镜子一样翻转图像',
    'settings.cameraPermissions': '相机权限',
    'settings.cameraPermissions.description': '在设置中管理相机访问权限',
    'settings.cape': '披风',
    'settings.capeOpacity': '披风不透明度',
    'settings.capeOpacity.description': '颜色叠加层的可见程度',
    'settings.opacity.light': '淡',
    'settings.opacity.medium': '中',
    'settings.opacity.strong': '强',
    'settings.opacity.full': '全',
    'settings.share': '分享',
    'settings.shareWithFriends': '分享给朋友',
    'settings.shareWithFriends.description': '传播 Color Cape 的消息',
    'settings.subscription': '订阅',
    'settings.manageSubscription': '管理订阅',
    'settings.manageSubscription.description': '查看或管理您的订阅',
    'settings.appData': '应用数据',
    'settings.clearLastViewed': '清除上次查看的调色板',
    'settings.clearLastViewed.description': '从主页移除上次查看的调色板',
    'settings.clearLastViewed.empty': '没有可清除的上次查看记录',
    'settings.clearSavedResult': '清除保存的测试结果',
    'settings.clearSavedResult.description': '移除您保存的季节色彩结果',
    'settings.clearSavedResult.empty': '没有可清除的测试结果',
    'settings.resetSettings': '重置设置',
    'settings.resetSettings.description': '将相机和披风设置恢复为默认值',
    'settings.resetSettings.atDefaults': '设置已是默认值',
    'settings.logOut': '退出登录',
    'settings.legal': '法律信息',
    'settings.privacyPolicy': '隐私政策',
    'settings.termsOfService': '服务条款',
    // Alerts
    'alert.resetSettings.title': '重置设置',
    'alert.resetSettings.message': '这将重置相机、披风设置并删除自定义披风。确定吗？',
    'alert.cancel': '取消',
    'alert.reset': '重置',
    'alert.clear': '清除',
    'alert.clearLastViewed.title': '清除上次查看',
    'alert.clearLastViewed.message': '这将从主屏幕移除上次查看的调色板。确定吗？',
    'alert.clearSavedResult.title': '清除保存的结果',
    'alert.clearSavedResult.message': '这将从主屏幕移除您保存的测试结果。确定吗？',
    'alert.logOut.title': '退出登录',
    'alert.logOut.message': '这将清除您的引导进度并再次显示欢迎界面。',
    'alert.logOut.confirm': '退出登录',
    // Home screen
    'home.title': 'Color Cape',
    'home.subtitle': '发现你的完美色彩搭配',
    'home.tryPalettes': '试穿披风',
    'home.tryPalettes.description': '使用相机查看不同调色板在你身上的效果',
    'home.lastViewed': '上次查看：',
    'home.takeTest': '参加测试',
    'home.takeTest.description': '通过测试找到你的季节色彩',
    'home.lastSavedResult': '上次保存的结果：',
    'home.customizeCapes': '自定义披风',
    'home.customizeCapes.description': '切换调色板、重新排序、创建自定义披风',
    'home.capeOpacity': '披风不透明度',
    'home.capeOpacity.description': '调整颜色叠加的可见度',
    'home.current': '当前：',
    'home.opacity.sheet.title': '披风不透明度',
    'home.opacity.sheet.description': '选择相机上颜色叠加的可见程度',
    // Camera screen
    'camera.loading': '加载相机中...',
    'camera.permissionTitle': '需要相机权限',
    'camera.permissionText': '我们需要您的许可才能访问相机。',
    'camera.continue': '继续',
    'camera.noPalettes': '没有启用调色板。请在设置中启用。',
    'camera.goToSettings': '前往设置',
    'camera.back': '返回',
    'camera.save': '保存',
    'camera.saved': '已保存！',
    'camera.savedMessage': '带颜色叠加的照片已保存到相册。',
    'camera.permissionNeeded': '需要权限',
    'camera.permissionNeededMessage': '请授予保存照片到相册的权限。',
    'camera.error': '错误',
    'camera.errorSaving': '保存照片失败。',
    'camera.colorMode.all8': '全部8色',
    'camera.colorMode.core': '核心色',
    'camera.colorMode.accent': '强调色',
    'camera.customColors': '自定义颜色',
    'camera.colors': '色',
    // Test screen
    'test.loading': '加载相机中...',
    'test.permissionTitle': '需要相机权限',
    'test.permissionText': '我们需要您的许可来展示颜色在您身上的效果。',
    'test.continue': '继续',
    'test.intro.title': '找到你的颜色',
    'test.intro.subtitle': '回答6个快速问题，发现你的季节色彩',
    'test.intro.privacyNote': '您的照片保存在设备上，不会上传。',
    'test.intro.startButton': '开始测试',
    'test.intro.goHome': '返回首页',
    'test.capture.title': '拍照',
    'test.capture.subtitle': '这将用于所有比较',
    'test.capture.instruction': '将自己定位在披风轮廓内',
    'test.confirm.title': '看起来不错！',
    'test.confirm.subtitle': '准备开始色彩测试了吗？',
    'test.confirm.retake': '重拍',
    'test.confirm.start': '确认并开始',
    'test.compare.swipeHint': '滑动比较',
    'test.compare.choose': '选择',
    'test.modal.youSelected': '您选择了',
    'test.modal.cancel': '取消',
    'test.modal.confirm': '确认',
    'test.transition.guide': '指南：',
    'test.transition.lookFor': '注意：',
    'test.transition.back': '返回',
    'test.transition.next': '下一步',
    'test.results.colorProfile': '您的色彩档案',
    'test.results.undertone': '底色：',
    'test.results.value': '明度：',
    'test.results.chroma': '纯度：',
    'test.results.yourMatches': '您的匹配',
    'test.results.tapToPreview': '点击预览颜色',
    'test.results.best': '最佳',
    'test.results.stylingTips': '造型建议',
    'test.results.saveResult': '保存结果',
    'test.results.saved': '已保存！',
    'test.results.retakeTest': '重新测试',
    'test.score.cool': '冷色',
    'test.score.warm': '暖色',
    'test.score.neutral': '中性',
    'test.score.light': '浅色',
    'test.score.deep': '深色',
    'test.score.medium': '中等',
    'test.score.bright': '明亮',
    'test.score.soft': '柔和',
    'test.transition.undertone': '底色',
    'test.transition.value': '明度',
    'test.transition.chroma': '纯度',
    'test.transition.undertone.title': '底色测试',
    'test.transition.undertone.desc': '让我们看看你是暖色还是冷色底调',
    'test.transition.value.title': '明度测试',
    'test.transition.value.desc': '现在让我们看看浅色还是深色更适合你',
    'test.transition.chroma.title': '纯度测试',
    'test.transition.chroma.desc': '最后，明亮清晰的颜色还是柔和的色调？',
    // Customize screen
    'customize.title': '自定义披风',
    'customize.customCapes': '自定义披风',
    'customize.customCapes.description': '创建你自己的颜色披风调色板',
    'customize.createCustomCape': '创建自定义披风',
    'customize.allPalettes': '所有调色板',
    'customize.allPalettes.description': '切换和重新排序你的披风',
    'customize.disableAll': '全部禁用',
    'customize.enableAll': '全部启用',
    'customize.resetToDefaults': '重置为默认',
    'customize.modal.createTitle': '创建自定义披风',
    'customize.modal.editTitle': '编辑自定义披风',
    'customize.modal.capeName': '披风名称',
    'customize.modal.capeNamePlaceholder': '输入披风名称',
    'customize.modal.numberOfColors': '颜色数量',
    'customize.modal.tapToEdit': '点击颜色进行编辑',
    'customize.modal.chooseColor': '选择颜色',
    'customize.modal.tapToPickColor': '点击选择颜色',
    'customize.modal.quickColors': '快速颜色',
    'customize.modal.importExport': '导入/导出',
    'customize.modal.import': '导入',
    'customize.modal.export': '导出',
    'customize.modal.delete': '删除',
    'customize.modal.saveCape': '保存披风',
    'customize.import.title': '导入披风',
    'customize.import.description': '在下方粘贴导出的披风JSON数据',
    'customize.import.paste': '从剪贴板粘贴',
    'customize.alert.deleteTitle': '删除自定义披风',
    'customize.alert.deleteMessage': '确定要删除这个自定义披风吗？',
    'customize.alert.delete': '删除',
    'customize.alert.resetTitle': '重置调色板',
    'customize.alert.resetMessage': '这将把所有调色板设置重置为默认值。确定吗？',
    'customize.colors': '色',
  },
  ja: {
    // Onboarding
    'onboarding.back': '戻る',
    'onboarding.q1.question': 'どちらが好みですか...',
    'onboarding.q1.opt1': 'ニュートラルカラー',
    'onboarding.q1.opt2': 'カラフル',
    'onboarding.q1.opt3': 'ニュートラル中心で少しカラー',
    'onboarding.q1.opt4': 'もっと実験したい',
    'onboarding.q2.question': '買い物中、色の選択に圧倒されることはありますか？',
    'onboarding.q2.opt1': 'はい、いつも！',
    'onboarding.q2.opt2': '時々',
    'onboarding.q2.opt3': 'あまりない',
    'onboarding.q2.opt4': '適当に選ぶ',
    'onboarding.q3.question': 'パーソナルカラー診断を受けたことはありますか？',
    'onboarding.q3.opt1': 'はい、季節タイプを知っています',
    'onboarding.q3.opt2': 'はい、でも結果を忘れました',
    'onboarding.q3.opt3': 'いいえ、でもやってみたい！',
    'onboarding.q3.opt4': 'いいえ、それは何ですか？',
    'onboarding.q4.question': '自分に色を試してみたいですか？',
    'onboarding.q4.opt1': 'はい、素敵ですね！',
    'onboarding.q4.opt2': '興味があります',
    'onboarding.q4.opt3': '簡単なら、やってみたい',
    'onboarding.q4.opt4': '後で',
    // Settings
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.language.description': 'アプリの言語を変更',
    'settings.availableCapes': '利用可能なケープ',
    'settings.capePalettes': 'ケープパレット',
    'settings.capePalettes.enabled': '有効',
    'settings.createCustomCape': 'カスタムケープを作成',
    'settings.createCustomCape.description': '自分だけのパレットをデザイン',
    'settings.camera': 'カメラ',
    'settings.defaultFrontCamera': 'デフォルトでフロントカメラ',
    'settings.defaultFrontCamera.description': 'ケープを開くときにフロントカメラを使用',
    'settings.mirrorFrontCamera': 'フロントカメラをミラー',
    'settings.mirrorFrontCamera.description': '鏡のように画像を反転',
    'settings.cameraPermissions': 'カメラの権限',
    'settings.cameraPermissions.description': '設定でカメラアクセスを管理',
    'settings.cape': 'ケープ',
    'settings.capeOpacity': 'ケープの不透明度',
    'settings.capeOpacity.description': 'カラーオーバーレイの表示度',
    'settings.opacity.light': '薄い',
    'settings.opacity.medium': '中',
    'settings.opacity.strong': '濃い',
    'settings.opacity.full': '完全',
    'settings.share': '共有',
    'settings.shareWithFriends': '友達と共有',
    'settings.shareWithFriends.description': 'Color Capeを広めよう',
    'settings.subscription': 'サブスクリプション',
    'settings.manageSubscription': 'サブスクリプションを管理',
    'settings.manageSubscription.description': 'サブスクリプションの表示・管理',
    'settings.appData': 'アプリデータ',
    'settings.clearLastViewed': '最後に見たパレットをクリア',
    'settings.clearLastViewed.description': 'ホームから最後に見たパレットを削除',
    'settings.clearLastViewed.empty': 'クリアする履歴がありません',
    'settings.clearSavedResult': '保存した結果をクリア',
    'settings.clearSavedResult.description': '保存した季節カラー結果を削除',
    'settings.clearSavedResult.empty': 'クリアする結果がありません',
    'settings.resetSettings': '設定をリセット',
    'settings.resetSettings.description': 'カメラとケープ設定をデフォルトに戻す',
    'settings.resetSettings.atDefaults': '設定は既にデフォルトです',
    'settings.logOut': 'ログアウト',
    'settings.legal': '法的情報',
    'settings.privacyPolicy': 'プライバシーポリシー',
    'settings.termsOfService': '利用規約',
    // Alerts
    'alert.resetSettings.title': '設定をリセット',
    'alert.resetSettings.message': 'カメラ、ケープ設定をリセットし、カスタムケープを削除します。よろしいですか？',
    'alert.cancel': 'キャンセル',
    'alert.reset': 'リセット',
    'alert.clear': 'クリア',
    'alert.clearLastViewed.title': '履歴をクリア',
    'alert.clearLastViewed.message': 'ホーム画面から最後に見たパレットを削除します。よろしいですか？',
    'alert.clearSavedResult.title': '結果をクリア',
    'alert.clearSavedResult.message': 'ホーム画面から保存した結果を削除します。よろしいですか？',
    'alert.logOut.title': 'ログアウト',
    'alert.logOut.message': 'オンボーディングの進行状況がクリアされ、ウェルカム画面が再度表示されます。',
    'alert.logOut.confirm': 'ログアウト',
    // Home screen
    'home.title': 'Color Cape',
    'home.subtitle': 'あなたにぴったりの色を見つけよう',
    'home.tryPalettes': 'パレットを試す',
    'home.tryPalettes.description': 'カメラを使って様々なパレットがあなたにどう見えるかチェック',
    'home.lastViewed': '最後に見た：',
    'home.takeTest': 'テストを受ける',
    'home.takeTest.description': 'テストであなたの季節カラーを見つけよう',
    'home.lastSavedResult': '保存した結果：',
    'home.customizeCapes': 'ケープをカスタマイズ',
    'home.customizeCapes.description': 'パレットの切替、並べ替え、カスタムケープの作成',
    'home.capeOpacity': 'ケープの不透明度',
    'home.capeOpacity.description': 'カラーオーバーレイの表示度を調整',
    'home.current': '現在：',
    'home.opacity.sheet.title': 'ケープの不透明度',
    'home.opacity.sheet.description': 'カメラ上のカラーオーバーレイの表示度を選択',
    // Camera screen
    'camera.loading': 'カメラ読み込み中...',
    'camera.permissionTitle': 'カメラへのアクセスが必要です',
    'camera.permissionText': 'カメラにアクセスするには許可が必要です。',
    'camera.continue': '続ける',
    'camera.noPalettes': 'パレットが有効になっていません。設定で有効にしてください。',
    'camera.goToSettings': '設定へ',
    'camera.back': '戻る',
    'camera.save': '保存',
    'camera.saved': '保存しました！',
    'camera.savedMessage': 'カラーオーバーレイ付きの写真がギャラリーに保存されました。',
    'camera.permissionNeeded': '許可が必要です',
    'camera.permissionNeededMessage': 'ギャラリーに写真を保存する許可を与えてください。',
    'camera.error': 'エラー',
    'camera.errorSaving': '写真の保存に失敗しました。',
    'camera.colorMode.all8': '全8色',
    'camera.colorMode.core': 'コア',
    'camera.colorMode.accent': 'アクセント',
    'camera.customColors': 'カスタム色',
    'camera.colors': '色',
    // Test screen
    'test.loading': 'カメラ読み込み中...',
    'test.permissionTitle': 'カメラへのアクセスが必要です',
    'test.permissionText': '色があなたにどう見えるかを表示するには許可が必要です。',
    'test.continue': '続ける',
    'test.intro.title': 'あなたの色を見つけよう',
    'test.intro.subtitle': '6つの質問に答えて、あなたの季節カラーを発見',
    'test.intro.privacyNote': '写真はデバイス上に保存され、アップロードされません。',
    'test.intro.startButton': 'テスト開始',
    'test.intro.goHome': 'ホームに戻る',
    'test.capture.title': '写真を撮る',
    'test.capture.subtitle': 'すべての比較に使用されます',
    'test.capture.instruction': 'ケープの輪郭内に自分を配置してください',
    'test.confirm.title': 'いい感じです！',
    'test.confirm.subtitle': 'カラーテストを始める準備はできましたか？',
    'test.confirm.retake': '撮り直す',
    'test.confirm.start': '確認して開始',
    'test.compare.swipeHint': 'スワイプして比較',
    'test.compare.choose': '選択',
    'test.modal.youSelected': '選択しました',
    'test.modal.cancel': 'キャンセル',
    'test.modal.confirm': '確認',
    'test.transition.guide': 'ガイド：',
    'test.transition.lookFor': '注目点：',
    'test.transition.back': '戻る',
    'test.transition.next': '次へ',
    'test.results.colorProfile': 'あなたのカラープロファイル',
    'test.results.undertone': 'アンダートーン：',
    'test.results.value': '明度：',
    'test.results.chroma': '彩度：',
    'test.results.yourMatches': 'あなたに合う色',
    'test.results.tapToPreview': 'タップして色をプレビュー',
    'test.results.best': 'ベスト',
    'test.results.stylingTips': 'スタイリングのヒント',
    'test.results.saveResult': '結果を保存',
    'test.results.saved': '保存しました！',
    'test.results.retakeTest': 'テストをやり直す',
    'test.score.cool': 'クール',
    'test.score.warm': 'ウォーム',
    'test.score.neutral': 'ニュートラル',
    'test.score.light': 'ライト',
    'test.score.deep': 'ディープ',
    'test.score.medium': 'ミディアム',
    'test.score.bright': 'ブライト',
    'test.score.soft': 'ソフト',
    'test.transition.undertone': 'アンダートーン',
    'test.transition.value': '明度',
    'test.transition.chroma': '彩度',
    'test.transition.undertone.title': 'アンダートーンテスト',
    'test.transition.undertone.desc': 'ウォームかクールのアンダートーンを見つけましょう',
    'test.transition.value.title': '明度テスト',
    'test.transition.value.desc': 'ライトかディープ、どちらの色が似合うか見てみましょう',
    'test.transition.chroma.title': '彩度テスト',
    'test.transition.chroma.desc': '最後に、鮮やかな色かソフトな色調か？',
    // Customize screen
    'customize.title': 'ケープをカスタマイズ',
    'customize.customCapes': 'カスタムケープ',
    'customize.customCapes.description': '自分だけのカラーケープパレットを作成',
    'customize.createCustomCape': 'カスタムケープを作成',
    'customize.allPalettes': 'すべてのパレット',
    'customize.allPalettes.description': 'ケープの切替と並べ替え',
    'customize.disableAll': 'すべて無効',
    'customize.enableAll': 'すべて有効',
    'customize.resetToDefaults': 'デフォルトにリセット',
    'customize.modal.createTitle': 'カスタムケープを作成',
    'customize.modal.editTitle': 'カスタムケープを編集',
    'customize.modal.capeName': 'ケープ名',
    'customize.modal.capeNamePlaceholder': 'ケープ名を入力',
    'customize.modal.numberOfColors': '色の数',
    'customize.modal.tapToEdit': '色をタップして編集',
    'customize.modal.chooseColor': '色を選択',
    'customize.modal.tapToPickColor': 'タップして色を選択',
    'customize.modal.quickColors': 'クイックカラー',
    'customize.modal.importExport': 'インポート/エクスポート',
    'customize.modal.import': 'インポート',
    'customize.modal.export': 'エクスポート',
    'customize.modal.delete': '削除',
    'customize.modal.saveCape': 'ケープを保存',
    'customize.import.title': 'ケープをインポート',
    'customize.import.description': 'エクスポートしたケープのJSONデータを貼り付けてください',
    'customize.import.paste': 'クリップボードから貼り付け',
    'customize.alert.deleteTitle': 'カスタムケープを削除',
    'customize.alert.deleteMessage': 'このカスタムケープを削除してもよろしいですか？',
    'customize.alert.delete': '削除',
    'customize.alert.resetTitle': 'パレットをリセット',
    'customize.alert.resetMessage': 'すべてのパレット設定をデフォルトにリセットします。よろしいですか？',
    'customize.colors': '色',
  },
  ko: {
    // Onboarding
    'onboarding.back': '뒤로',
    'onboarding.q1.question': '어떤 것을 선호하시나요...',
    'onboarding.q1.opt1': '뉴트럴 컬러',
    'onboarding.q1.opt2': '컬러풀',
    'onboarding.q1.opt3': '주로 뉴트럴에 약간의 컬러',
    'onboarding.q1.opt4': '더 많이 실험해보고 싶어요',
    'onboarding.q2.question': '쇼핑할 때 색상 선택에 압도당한 적이 있나요?',
    'onboarding.q2.opt1': '네, 항상요!',
    'onboarding.q2.opt2': '가끔요',
    'onboarding.q2.opt3': '별로 그렇지 않아요',
    'onboarding.q2.opt4': '그냥 집어요',
    'onboarding.q3.question': '퍼스널 컬러 진단을 받아본 적이 있나요?',
    'onboarding.q3.opt1': '네, 제 시즌을 알아요',
    'onboarding.q3.opt2': '네, 하지만 결과를 잊어버렸어요',
    'onboarding.q3.opt3': '아니요, 하지만 해보고 싶어요!',
    'onboarding.q3.opt4': '아니요, 그게 뭐예요?',
    'onboarding.q4.question': '자신에게 색상을 입혀보고 싶으세요?',
    'onboarding.q4.opt1': '네, 정말 좋겠어요!',
    'onboarding.q4.opt2': '네, 궁금해요',
    'onboarding.q4.opt3': '쉽다면요',
    'onboarding.q4.opt4': '나중에요',
    // Settings
    'settings.title': '설정',
    'settings.language': '언어',
    'settings.language.description': '앱 언어 변경',
    'settings.availableCapes': '사용 가능한 케이프',
    'settings.capePalettes': '케이프 팔레트',
    'settings.capePalettes.enabled': '활성화됨',
    'settings.createCustomCape': '커스텀 케이프 만들기',
    'settings.createCustomCape.description': '나만의 팔레트 디자인',
    'settings.camera': '카메라',
    'settings.defaultFrontCamera': '기본 전면 카메라',
    'settings.defaultFrontCamera.description': '케이프 열 때 전면 카메라 사용',
    'settings.mirrorFrontCamera': '전면 카메라 미러링',
    'settings.mirrorFrontCamera.description': '거울처럼 이미지 뒤집기',
    'settings.cameraPermissions': '카메라 권한',
    'settings.cameraPermissions.description': '설정에서 카메라 접근 관리',
    'settings.cape': '케이프',
    'settings.capeOpacity': '케이프 불투명도',
    'settings.capeOpacity.description': '컬러 오버레이 표시 정도',
    'settings.opacity.light': '연함',
    'settings.opacity.medium': '중간',
    'settings.opacity.strong': '진함',
    'settings.opacity.full': '완전',
    'settings.share': '공유',
    'settings.shareWithFriends': '친구와 공유',
    'settings.shareWithFriends.description': 'Color Cape 알리기',
    'settings.subscription': '구독',
    'settings.manageSubscription': '구독 관리',
    'settings.manageSubscription.description': '구독 보기 또는 관리',
    'settings.appData': '앱 데이터',
    'settings.clearLastViewed': '마지막 본 팔레트 지우기',
    'settings.clearLastViewed.description': '홈에서 마지막 본 팔레트 제거',
    'settings.clearLastViewed.empty': '지울 기록이 없습니다',
    'settings.clearSavedResult': '저장된 결과 지우기',
    'settings.clearSavedResult.description': '저장된 시즌 컬러 결과 제거',
    'settings.clearSavedResult.empty': '지울 결과가 없습니다',
    'settings.resetSettings': '설정 초기화',
    'settings.resetSettings.description': '카메라 및 케이프 설정을 기본값으로 복원',
    'settings.resetSettings.atDefaults': '이미 기본 설정입니다',
    'settings.logOut': '로그아웃',
    'settings.legal': '법적 정보',
    'settings.privacyPolicy': '개인정보 처리방침',
    'settings.termsOfService': '서비스 약관',
    // Alerts
    'alert.resetSettings.title': '설정 초기화',
    'alert.resetSettings.message': '카메라, 케이프 설정을 초기화하고 커스텀 케이프를 삭제합니다. 계속하시겠습니까?',
    'alert.cancel': '취소',
    'alert.reset': '초기화',
    'alert.clear': '지우기',
    'alert.clearLastViewed.title': '기록 지우기',
    'alert.clearLastViewed.message': '홈 화면에서 마지막 본 팔레트를 제거합니다. 계속하시겠습니까?',
    'alert.clearSavedResult.title': '결과 지우기',
    'alert.clearSavedResult.message': '홈 화면에서 저장된 결과를 제거합니다. 계속하시겠습니까?',
    'alert.logOut.title': '로그아웃',
    'alert.logOut.message': '온보딩 진행 상황이 지워지고 환영 화면이 다시 표시됩니다.',
    'alert.logOut.confirm': '로그아웃',
    // Home screen
    'home.title': 'Color Cape',
    'home.subtitle': '완벽한 컬러 팔레트를 찾아보세요',
    'home.tryPalettes': '팔레트 체험',
    'home.tryPalettes.description': '카메라로 다양한 팔레트가 어떻게 보이는지 확인',
    'home.lastViewed': '마지막 조회:',
    'home.takeTest': '테스트 받기',
    'home.takeTest.description': '테스트로 당신의 시즌 컬러를 찾아보세요',
    'home.lastSavedResult': '저장된 결과:',
    'home.customizeCapes': '케이프 커스텀',
    'home.customizeCapes.description': '팔레트 전환, 재정렬, 커스텀 케이프 만들기',
    'home.capeOpacity': '케이프 불투명도',
    'home.capeOpacity.description': '컬러 오버레이의 표시 정도 조절',
    'home.current': '현재:',
    'home.opacity.sheet.title': '케이프 불투명도',
    'home.opacity.sheet.description': '카메라에서 컬러 오버레이의 표시 정도 선택',
    // Camera screen
    'camera.loading': '카메라 로딩 중...',
    'camera.permissionTitle': '카메라 접근 필요',
    'camera.permissionText': '카메라에 접근하려면 권한이 필요합니다.',
    'camera.continue': '계속',
    'camera.noPalettes': '활성화된 팔레트가 없습니다. 설정에서 활성화하세요.',
    'camera.goToSettings': '설정으로 이동',
    'camera.back': '뒤로',
    'camera.save': '저장',
    'camera.saved': '저장됨!',
    'camera.savedMessage': '컬러 오버레이가 적용된 사진이 갤러리에 저장되었습니다.',
    'camera.permissionNeeded': '권한 필요',
    'camera.permissionNeededMessage': '갤러리에 사진을 저장할 권한을 허용해주세요.',
    'camera.error': '오류',
    'camera.errorSaving': '사진 저장에 실패했습니다.',
    'camera.colorMode.all8': '전체 8색',
    'camera.colorMode.core': '코어',
    'camera.colorMode.accent': '악센트',
    'camera.customColors': '커스텀 색상',
    'camera.colors': '색',
    // Test screen
    'test.loading': '카메라 로딩 중...',
    'test.permissionTitle': '카메라 접근 필요',
    'test.permissionText': '색상이 당신에게 어떻게 보이는지 표시하려면 권한이 필요합니다.',
    'test.continue': '계속',
    'test.intro.title': '당신의 컬러를 찾아보세요',
    'test.intro.subtitle': '6가지 질문에 답하고 당신의 시즌 컬러를 발견하세요',
    'test.intro.privacyNote': '사진은 기기에만 저장되며 업로드되지 않습니다.',
    'test.intro.startButton': '테스트 시작',
    'test.intro.goHome': '홈으로 돌아가기',
    'test.capture.title': '사진 찍기',
    'test.capture.subtitle': '모든 비교에 사용됩니다',
    'test.capture.instruction': '케이프 윤곽 안에 위치하세요',
    'test.confirm.title': '좋아 보여요!',
    'test.confirm.subtitle': '컬러 테스트를 시작할 준비가 되셨나요?',
    'test.confirm.retake': '다시 찍기',
    'test.confirm.start': '확인 후 시작',
    'test.compare.swipeHint': '스와이프하여 비교',
    'test.compare.choose': '선택',
    'test.modal.youSelected': '선택하셨습니다',
    'test.modal.cancel': '취소',
    'test.modal.confirm': '확인',
    'test.transition.guide': '가이드:',
    'test.transition.lookFor': '주목할 점:',
    'test.transition.back': '뒤로',
    'test.transition.next': '다음',
    'test.results.colorProfile': '당신의 컬러 프로필',
    'test.results.undertone': '언더톤:',
    'test.results.value': '명도:',
    'test.results.chroma': '채도:',
    'test.results.yourMatches': '당신에게 어울리는 색',
    'test.results.tapToPreview': '탭하여 색상 미리보기',
    'test.results.best': '베스트',
    'test.results.stylingTips': '스타일링 팁',
    'test.results.saveResult': '결과 저장',
    'test.results.saved': '저장됨!',
    'test.results.retakeTest': '테스트 다시 하기',
    'test.score.cool': '쿨톤',
    'test.score.warm': '웜톤',
    'test.score.neutral': '뉴트럴',
    'test.score.light': '라이트',
    'test.score.deep': '딥',
    'test.score.medium': '미디엄',
    'test.score.bright': '브라이트',
    'test.score.soft': '소프트',
    'test.transition.undertone': '언더톤',
    'test.transition.value': '명도',
    'test.transition.chroma': '채도',
    'test.transition.undertone.title': '언더톤 테스트',
    'test.transition.undertone.desc': '웜톤인지 쿨톤인지 알아볼까요',
    'test.transition.value.title': '명도 테스트',
    'test.transition.value.desc': '라이트한 색상과 딥한 색상 중 어떤 것이 더 어울리는지 봅시다',
    'test.transition.chroma.title': '채도 테스트',
    'test.transition.chroma.desc': '마지막으로, 선명한 색상 vs 소프트한 톤?',
    // Customize screen
    'customize.title': '케이프 커스텀',
    'customize.customCapes': '커스텀 케이프',
    'customize.customCapes.description': '나만의 컬러 케이프 팔레트 만들기',
    'customize.createCustomCape': '커스텀 케이프 만들기',
    'customize.allPalettes': '모든 팔레트',
    'customize.allPalettes.description': '케이프 전환 및 재정렬',
    'customize.disableAll': '모두 비활성화',
    'customize.enableAll': '모두 활성화',
    'customize.resetToDefaults': '기본값으로 초기화',
    'customize.modal.createTitle': '커스텀 케이프 만들기',
    'customize.modal.editTitle': '커스텀 케이프 편집',
    'customize.modal.capeName': '케이프 이름',
    'customize.modal.capeNamePlaceholder': '케이프 이름 입력',
    'customize.modal.numberOfColors': '색상 수',
    'customize.modal.tapToEdit': '색상을 탭하여 편집',
    'customize.modal.chooseColor': '색상 선택',
    'customize.modal.tapToPickColor': '탭하여 색상 선택',
    'customize.modal.quickColors': '빠른 색상',
    'customize.modal.importExport': '가져오기/내보내기',
    'customize.modal.import': '가져오기',
    'customize.modal.export': '내보내기',
    'customize.modal.delete': '삭제',
    'customize.modal.saveCape': '케이프 저장',
    'customize.import.title': '케이프 가져오기',
    'customize.import.description': '내보낸 케이프 JSON 데이터를 아래에 붙여넣으세요',
    'customize.import.paste': '클립보드에서 붙여넣기',
    'customize.alert.deleteTitle': '커스텀 케이프 삭제',
    'customize.alert.deleteMessage': '이 커스텀 케이프를 삭제하시겠습니까?',
    'customize.alert.delete': '삭제',
    'customize.alert.resetTitle': '팔레트 초기화',
    'customize.alert.resetMessage': '모든 팔레트 설정을 기본값으로 초기화합니다. 계속하시겠습니까?',
    'customize.colors': '색',
  },
};

const LANGUAGE_STORAGE_KEY = 'app_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLang && ['en', 'zh', 'ja', 'ko'].includes(savedLang)) {
        setLanguageState(savedLang as LanguageCode);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const setLanguage = async (lang: LanguageCode) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isLoading, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
